version: 1.0.{build}
image: Ubuntu1804
init:
- pwsh: Get-ChildItem ENV:\
install:
- pwsh: # Install-Module -Name Pester -Scope CurrentUser -Force  
build: off
test_script:
- pwsh: '& .\CI\Invoke-Test.ps1 -AppVeyor -ExcludeTag GH-1461'
deploy_script:
- pwsh: >-
    & .\Mock\Register-MockRepository.ps1
    
    & .\CI\Publish-Module.ps1 -UseMock

    & .\CI\Publish-Script.ps1 -UseMock    