version: 1.0.{build}
image: Ubuntu1804
init:
- pwsh: Get-ChildItem ENV:\
install:
- pwsh: >-
    Install-Module -Name XWrite -Scope CurrentUser -Force
    
    Set-XGlobalTrace -ForVerbose
    
    Enable-XWriteProgress -UseHost -ForegroundColor Green
    
    Enable-XWrite -ForVerbose
build: off
test_script:
- pwsh: '& .\CI\Test-Module.ps1 -AppVeyor'
artifacts:
- path: Src\Modules\M1\**
  name: M1
- path: Src\Modules\M2\**
  name: M2
deploy_script:
- pwsh: >-
    & .\Mock\Register-MockRepository.ps1

    & .\CI\Publish-Module.ps1 -UseMock -KeepManifests
