version: 1.0.{build}
image: Ubuntu1804
init:
- pwsh: '& .\CI\AppVeyor\Init-Script.ps1'
install:
- pwsh: '& ./CI/AppVeyor/Install-Script.ps1'
build: off
test_script:
- pwsh: '& .\CI\Test-Module.ps1 -EnableExit -PassThru'
artifacts:
- path: Src\Modules\M1\**
  name: M1
- path: Src\Modules\M2\**
  name: M2
deploy_script:
- pwsh: >-
    & .\Mock\Register-MockRepository.ps1

    & .\CI\Publish-Module.ps1 -UseMock -KeepManifests