version: 1.0.{build}
image: Ubuntu1804
init:
- pwsh: Get-ChildItem ENV:\
install:
- pwsh: >-
    $modules=@(
      # "Pester"
      "SemVerPS"
    )
    
    $modules|ForEach-Object {Install-Module -Name $_ -Scope CurrentUser -Force}

    Get-Module -Name $modules -ListAvailable|Format-Table Name,Version,Path
build: off
test_script:
- pwsh: '& .\CI\Invoke-Test.ps1 -AppVeyor -ExcludeTag GH-1461'
deploy_script:
- pwsh: >-
    & .\CI\Publish-Module.ps1

    & .\CI\Publish-Script.ps1
notifications:
  - provider: GitHubPullRequest
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
